#!/bin/bash
#PBS -l mem=96gb,nodes=1:ppn=16,walltime=24:00:00
#PBS -A hirschc1
#PBS -m abe
#PBS -M konox006@umn.edu
#PBS -q sb128

#   Load modules and versions
module load python-epd/1.5.2
module load mcl/10.201
module load ncbi_blast+/2.6.0
module load mafft/7.305
module load fasttree/2.1.8

#   This is Orthofinder 1.1.5
#   -a 24: 24 orthofinder threads
#   -t 24: 24 blast/align/tree threads

#   Uncomment this command to perform the BLAST searches with the FASTA, and
#   store the results.
#python /home/hirschc1/konox006/Software/OrthoFinder/orthofinder/orthofinder.py \
#    -f /panfs/roc/scratch/tk_maize/Fractionation/Tandem_Duplicates/Evol_Tests/Ortho_Base \
#    -a 24 \
#    -t 24 

#   Uncomment this command to parse the BLAST results and generate orthogroups
#   and orthologues for pairwise combinations of species.
python /home/hirschc1/konox006/Software/OrthoFinder/orthofinder/orthofinder.py \
    -b /panfs/roc/scratch/tk_maize/Fractionation/Tandem_Duplicates/Evol_Tests/Ortho_Base/Results_Apr21/WorkingDirectory/ \
    -a 16 \
    -t 16 
